#
# Module manifest for module 'MeasureRows'
#
# Generated by: florian.von.bracht@apteco.de
#
# Generated on: 03.11.2022
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'ExtendFunction.psm1'

# Version number of this module.
ModuleVersion = '0.9.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '722bc3eb-8231-45fd-b4c1-b0fe86b14ba9'

# Author of this module
Author = 'florian.von.bracht@apteco.de'

# Company or vendor of this module
CompanyName = 'Apteco GmbH'

# Copyright statement for this module
Copyright = '(c) 2025 Apteco GmbH. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Apteco PS Modules - PowerShell functions extension

This function helps to gather all parameters that a function/cmdlet has
except the common parameters like -verbose etc.

This can be used to extend existing functions/cmdlets with more scripting
and possibly additional parameters.

So in this example you see how it works

```PowerShell

# These functions inherit the parameters of the original functions/cmdlets
# And as an example adds an additional parameter
# There are two functions for the different PowerShell Editions

function Invoke-DesktopWebRequest {

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true)][string]$AdditionalString
    )
    DynamicParam { Get-BaseParameters "Invoke-WebRequest" }

    Process {
        Write-Host "Using `$PSEdition: Desktop"
        Write-Host $AdditionalString
        $updatedParameters = Skip-UnallowedBaseParameters -Base "Invoke-WebRequest" -Parameters $PSBoundParameters
        Invoke-WebRequest @updatedParameters

    }

}

function Invoke-CoreWebRequest {

    [CmdletBinding()]
    param (
        [Parameter(Mandatory=$true)][string]$AdditionalString
    )
    DynamicParam { Get-BaseParameters "Invoke-WebRequest" }

    Process {
        Write-Host "Using `$PSEdition: Core"
        Write-Host $AdditionalString
        $updatedParameters = Skip-UnallowedBaseParameters -Base "Invoke-WebRequest" -Parameters $PSBoundParameters
        Invoke-WebRequest @updatedParameters
    }

}

```

And this can be used like

```PowerShell

#-----------------------------------------------
# CREATE AN ALIAS DEPENDING ON $PSEdition
#-----------------------------------------------

# In this example differentiates between Core and Desktop, but creates one alias for different $PSEdition
# Just type $PSEdition if you want to know which edition you are using

Switch ( $PSEdition ) {

    "Desktop" {
        Set-Alias -Name Invoke-WebRequestExtended -Value Invoke-DesktopWebRequest -Force
    }

    "Core" {
        Set-Alias -Name Invoke-WebRequestExtended -Value Invoke-CoreWebRequest -Force
    }

}


#-----------------------------------------------
# EXAMPLE TO LOAD DATA WITH THE NEW ALIAS
#-----------------------------------------------

$myParams = [Hashtable]@{
    Uri = "https://api.chucknorris.io/jokes/random"
    Method = "Get"
    Verbose = $true
    AdditionalString = "Hello World"
}
$wr = Invoke-WebRequestExtended @myParams
( $wr.content | ConvertFrom-Json ).Value


```

'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = '*'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @("PSEdition_Desktop", "PSEdition_Core", "Windows", "Apteco")

        # A URL to the license for this module.
        LicenseUri = 'https://gist.github.com/gitfvb/58930387ee8677b5ccef93ffc115d836'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Apteco/AptecoPSModules/tree/main/ExtendFunction'

        # A URL to an icon representing this module.
        IconUri = 'https://www.apteco.de/sites/default/files/favicon_3.ico'

        # ReleaseNotes of this module
        ReleaseNotes = '
0.9.1 Updated copyright to 2025
0.9.0 Initial release of extending functions module through psgallery
'
        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

