name: MeasureRows Pester Tests

on:
  push:
    branches:
      - dev
    paths:
      - 'MeasureRows/**.ps1'
      - 'MeasureRows/**.psm1'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        shell: [ pwsh ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up repositories
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
        shell: pwsh

      - name: Run Pester Tests (${{ matrix.shell }} on ${{ matrix.os }})
        env:
          CI: true
        shell: pwsh
        run: Invoke-Pester -Path MeasureRows/Tests/ -Output Detailed -Passthru
