name: MeasureRows Pester Tests

on:
  push:
    branches:
      - dev
    paths:
      - 'MeasureRows/**.ps1'
      - 'MeasureRows/**.psm1'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        shell: [ pwsh ]
        include:
          - os: windows-latest
            shell: powershell

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Set up repositories - powershell
        if: matrix.shell == 'powershell'
        shell: powershell
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted

      - name: Run Pester Tests (${{ matrix.shell }} on ${{ matrix.os }})
        if: matrix.shell == 'powershell'
        env:
          CI: true
        shell: powershell
        run: Invoke-Pester -Path MeasureRows/Tests/ -Output Detailed -Passthru

      - name: Set up repositories - pwsh
        if: matrix.shell != 'powershell'
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
        shell: pwsh

      - name: Run Pester Tests (${{ matrix.shell }} on ${{ matrix.os }})
        if: matrix.shell != 'powershell'
        env:
          CI: true
        shell: pwsh
        run: Invoke-Pester -Path MeasureRows/Tests/ -Output Detailed -Passthru